[package]
name = "wasi-document-unzip"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "unzip"
# crate-type = ["cdylib"]

[dependencies.zip]
version = "0.6.3"
default-features = false
features = ["deflate"]
