[package]
name = "wasi-document"
version = "0.0.0"
edition = "2024"

[dependencies]
clap.workspace = true
html_and_tar.workspace = true
serde.workspace = true
serde_json = "1"
toml.workspace = true
walkdir = "2.5"
wasi-document-dom.workspace = true

wasm-encoder = "0.20"
wasmparser = "0.95"
